version: '3.8'

services:
  constellation-ssh:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: constellation-ssh-server
    hostname: constellation-ssh
    ports:
      - "2222:22"  # SSH port mapping to avoid conflicts with host SSH
    volumes:
      # Mount workspace for persistence
      - ./workspace:/workspace/projects
      # Mount SSH keys if they exist (created by setup script)
      - ./keys:/keys:ro
      # Mount shared directory for file transfers
      - ./shared:/workspace/shared
    environment:
      - DEBIAN_FRONTEND=noninteractive
      - SSH_USER=root
      - WORKSPACE_PATH=/workspace
    networks:
      - constellation-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "service", "ssh", "status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  constellation-network:
    driver: bridge
    name: constellation-fs-network

volumes:
  # Named volume for workspace persistence
  constellation-workspace:
    name: constellation-fs-workspace